package de.elite.games.yatzee.ai;

public enum Strategy {

    ROLL_FOR_IDENTICAL, ROLL_FOR_FIVE_AND_SIX, ROLL_FOR_SIX, ROLL_FOR_FIVE,
    REROLL_ALL, ROLL_FOR_MAJOR_STRAIGHT, ROLL_FOR_MINOR_STRAIGHT
}
